# unpinned yields
#
#   Built wheel for abi3 Python ≥ 3.7 to pyrudof-0.1.90-cp37-abi3-macosx_14_0_x86_64.whl
#
# then
#
#   pyrudof 0.1.90 is not supported on this platform
c_compiler_version:       # [osx and x86_64]
  - "19"                  # [osx and x86_64]
# hopefully not needed after feedstock?
MACOSX_DEPLOYMENT_TARGET: # [osx and x86_64]
  - "11.0"                # [osx and x86_64]
MACOSX_SDK_VERSION:       # [osx and x86_64]
  - "11.0"                # [osx and x86_64]
