# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.2.6"
  maturin_min: "1"
  maturin_max: "2"
  python_check_max: "3.14"
  # posix-ish stuff
  grep_version: ${{ "grep -iE" if unix else "findstr /r /c /i" }} "${{ version | replace('.', '\\.') }}"
  export: ${{ "export" if unix else "set" }}
  ls: ${{ "ls -lathr" if unix else "dir" }}
  # abi3audit
  abi3_ext: ${{ "pyd" if win else "abi3.so" }}
  unix_sp_dir: |-
    $(python -c "print(__import__('site').getsitepackages()[-1])")/pyrudof
  win_sp_dir: |-
    Lib\site-packages\pyrudof
  sp_dir: |-
    ${{ "%PREFIX%\\" ~ win_sp_dir if win else unix_sp_dir }}

recipe:
  name: rudof-split
  version: ${{ version }}

source:
  url: https://github.com/rudof-project/rudof/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 97a363367779e84af6b5e0444634b09c75d47c1f7b7ae80a1c0f1b958fb0b945

build:
  number: 0

outputs:
  - package:
      name: rudof
    build:
      skip: not is_python_min
      script:
        - ${{ export }} CARGO_PROFILE_RELEASE_STRIP=symbols
        - ${{ export }} "OPENSSL_DIR=${{ '$PREFIX' if unix else '%LIBRARY_PREFIX%' }}"
        - cd rudof_cli
        - cargo install --no-track --locked --path=. --profile=release "--root=${{ PREFIX }}"
        - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("rust") }}
        - ${{ stdlib("c") }}
        - cargo-bundle-licenses
        - make
        - pkg-config
        - if: win
          then:
            - perl
      host:
        - openssl
    tests:
      - script:
          - rudof --help
          - rudof --version
          - rudof --version | ${{ grep_version }}
    about:
      homepage: https://crates.io/crates/rudof_cli
      repository: https://github.com/rudof-project/rudof/tree/master/rudof_cli
      description: >
        rudof is a command-line tool to inspect and validate RDF data using ShEx
        or SHACL, and to allow conversion between different RDF data modeling
        languages like ShEx, SHACL, DCTAP, etc.
      license_file:
        - LICENSE-APACHE
        - LICENSE-MIT
        - rudof_cli/THIRDPARTY.yml

  - package:
      name: pyrudof
    build:
      skip: is_abi3 and not is_python_min
      python:
        version_independent: ${{ is_abi3 }}
      script:
        - ${{ export }} CARGO_PROFILE_RELEASE_STRIP=symbols
        - ${{ export }} "OPENSSL_DIR=${{ '$PREFIX' if unix else '%LIBRARY_PREFIX%' }}"
        - cd python
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
        - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("rust") }}
        - ${{ stdlib("c") }}
        - cargo-bundle-licenses
        - make
        - pkg-config
        - if: build_platform != target_platform
          then:
            - cross-python_${{ target_platform }}
            - maturin >=${{ maturin_min }},<${{ maturin_max }}
            - openssl
            - python
        - if: win
          then:
            - perl
      host:
        - maturin >=${{ maturin_min }},<${{ maturin_max }}
        - openssl
        - pip
        - python
        - if: is_abi3
          then:
            - python-abi3
      run:
        - python
      ignore_run_exports:
        from_package:
          - cross-python_${{ target_platform }}
    tests:
      - if: is_abi3
        then:
          python:
            imports: pyrudof
            pip_check: true
            python_version:
              - ${{ python_min }}.*
              - ${{ python_check_max }}.*
        else:
          python:
            imports: pyrudof
            pip_check: true
      - requirements:
          run:
            - pytest
            - if: is_abi3
              then:
                - abi3audit
                - python !=${{ python_min }}.*
        files:
          source:
            - python/tests/
        script:
          - python -c "print(__import__('pyrudof').__version__)" | ${{ grep_version }}
          - cd python
          - pytest -vv --tb=long --color=yes
          - if: is_abi3
            then:
              - cd "${{ sp_dir }}"
              - ${{ ls }}
              - abi3audit -s -v --assume-minimum-abi3 ${{ python_min }} pyrudof.${{ abi3_ext }}
    about:
      homepage: https://pypi.org/project/pyrudof
      repository: https://github.com/rudof-project/rudof/tree/master/python
      summary: Python bindings for Rudof, RDF data shapes implementation in Rust
      license_file:
        - LICENSE-APACHE
        - LICENSE-MIT
        - python/THIRDPARTY.yml

about:
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: RDF data shapes implementation in Rust
  homepage: https://github.com/rudof-project/rudof
  repository: https://github.com/rudof-project/rudof

extra:
  feedstock-name: rudof
  recipe-maintainers:
    - bollwyvl
