# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.2.1"
  maturin_min: "1"
  maturin_max: "2"
  python_check_max: "3.14"
  grep: ${{ "grep -iE" if unix else "findstr /r /c /i" }}

recipe:
  name: rudof-split
  version: ${{ version }}

source:
  url: https://github.com/rudof-project/rudof/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b9a830deaa829732dbd5fbb6c4f78f6d8aa6b726206d7a7d33acbe20c80ac14e

build:
  number: 0

outputs:
  - package:
      name: rudof
    build:
      script:
        file: build-rudof
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("rust") }}
        - ${{ stdlib("c") }}
        - cargo-bundle-licenses
        - make
        - pkg-config
        - if: win
          then:
            - perl
      host:
        - openssl
    tests:
      - script:
          - rudof --help
          - rudof --version
          - rudof --version  | ${{ grep }} "${{ version.replace(".", "\\") }}"
    about:
      license_file:
        - LICENSE-APACHE
        - LICENSE-MIT
        - THIRDPARTY.yml

  - package:
      name: pyrudof
    build:
      skip: is_abi3 and not is_python_min
      python:
        version_independent: ${{ is_abi3 }}
      script:
        file: build-pyrudof
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("rust") }}
        - ${{ stdlib("c") }}
        - cargo-bundle-licenses
        - make
        - pkg-config
        - if: build_platform != target_platform
          then:
            - cross-python_${{ target_platform }}
            - maturin >=${{ maturin_min }},<${{ maturin_max }}
            - openssl
            - python
        - if: win
          then:
            - perl
      host:
        - maturin >=${{ maturin_min }},<${{ maturin_max }}
        - openssl
        - pip
        - python
        - if: is_abi3
          then:
            - python-abi3
      run:
        - python
      ignore_run_exports:
        from_package:
          - cross-python_${{ target_platform }}
    tests:
      - if: is_abi3
        then:
          python:
            imports: pyrudof
            pip_check: true
            python_version:
              - ${{ python_min }}.*
              - ${{ python_check_max }}.*
        else:
          python:
            imports: pyrudof
            pip_check: true
      - requirements:
          run:
            - pytest-cov
            - if: is_abi3
              then:
                - python !=${{ python_min }}.*
        files:
          source:
            - python/tests/
        script:
          - cd python
          - coverage run --source=pyrudof --branch -m pytest -vv --tb=long --color=yes
          - coverage report --show-missing --skip-covered --fail-under=83
    about:
      license_file:
        - LICENSE-APACHE
        - LICENSE-MIT
        - THIRDPARTY.yml
      summary: This module contains the Python bindings of rudof which are called pyrudof

about:
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: |-
    rudof is a command-line tool to inspect and validate RDF data using ShEx or
    SHACL, and to allow conversion between different RDF data modeling languages
    like ShEx, SHACL, DCTAP, etc.
  homepage: https://github.com/rudof-project/rudof

extra:
  feedstock-name: rudof
  recipe-maintainers:
    - bollwyvl
